# Generated by Django 2.1.2 on 2018-10-22 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Init', 'init'), ('Active', 'Active'), ('Ignored', 'Ignored'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Init', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionInteractionFactory',
            fields=[
                ('interaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interactions.Interaction')),
            ],
            bases=('interactions.interaction',),
        ),
        migrations.CreateModel(
            name='SendTextOperation',
            fields=[
                ('interaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interactions.Interaction')),
            ],
            bases=('interactions.interaction',),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='interaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactions.Interaction'),
        ),
    ]
