# Generated by Django 2.1.2 on 2018-10-22 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='questioninteractionfactory',
            name='question',
            field=models.CharField(default='kek?', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questioninteractionfactory',
            name='slot_name',
            field=models.CharField(default='slot_name?', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendtextoperation',
            name='text',
            field=models.CharField(default='text is here', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='userdialog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interactions.UserDialog'),
            preserve_default=False,
        ),
    ]
