# Generated by Django 2.1.2 on 2018-11-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('validator', models.CharField(max_length=200)),
                ('normalizer', models.CharField(max_length=200)),
                ('receptor', models.CharField(max_length=200)),
                ('required', models.BooleanField()),
            ],
        ),
    ]
