# Generated by Django 2.1.2 on 2018-12-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_slotfield'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlotField',
        ),
    ]
