# Generated by Django 2.1.2 on 2018-10-22 11:45

from django.db import migrations, models
import django.db.models.deletion
import interactions.models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_auto_20181022_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='ByeInteraction',
            fields=[
                ('interaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interactions.Interaction')),
            ],
            bases=('interactions.interaction', interactions.models.AbstractInteraction),
        ),
        migrations.CreateModel(
            name='GreetInteraction',
            fields=[
                ('interaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interactions.Interaction')),
            ],
            bases=('interactions.interaction', interactions.models.AbstractInteraction),
        ),
    ]
