# Generated by Django 2.1.2 on 2018-12-20 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_dpuserprofile_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userslotprocess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactions.DPUserProfile'),
        ),
    ]
