# Generated by Django 2.1.2 on 2018-12-21 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_auto_20181220_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdialog',
            name='target_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interactions.DPUserProfile'),
            preserve_default=False,
        ),
    ]
