# Generated by Django 2.1.2 on 2019-02-01 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0006_userdialog_target_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlottyFormInteraction',
            fields=[
                ('interaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interactions.Interaction')),
            ],
            bases=('interactions.interaction',),
        ),
    ]
